name: Go Tests
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17.0'
      id: go

    - name: Check out code
      uses: actions/checkout@v2

    - name: Test
      run: |
        ( go test -race ./... )
